# Generated by Django 4.2.16 on 2024-10-21 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="user",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="seller",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="favorite",
            name="product",
        ),
        migrations.RemoveField(
            model_name="favorite",
            name="user",
        ),
        migrations.RemoveField(
            model_name="follower",
            name="followed",
        ),
        migrations.RemoveField(
            model_name="follower",
            name="follower",
        ),
        migrations.RemoveField(
            model_name="product",
            name="user",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Favorite",
        ),
        migrations.DeleteModel(
            name="Follower",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
