# Generated by Django 4.2.16 on 2024-10-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="items",
        ),
        migrations.AddField(
            model_name="cart",
            name="products",
            field=models.ManyToManyField(to="app.product"),
        ),
        migrations.AlterField(
            model_name="cart",
            name="total_price",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
