# Generated by Django 4.2.16 on 2024-10-22 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_cart_items_cart_products_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("total_price", models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name="favorite",
            name="product",
        ),
        migrations.RemoveField(
            model_name="favorite",
            name="user",
        ),
        migrations.RemoveField(
            model_name="follower",
            name="followed",
        ),
        migrations.RemoveField(
            model_name="follower",
            name="follower",
        ),
        migrations.AddField(
            model_name="user",
            name="cart",
            field=models.ManyToManyField(
                blank=True, related_name="carts", to="app.product"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="favorites",
            field=models.ManyToManyField(
                blank=True, related_name="favorited_users", to="app.product"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="following", to="app.user"
            ),
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="Favorite",
        ),
        migrations.DeleteModel(
            name="Follower",
        ),
        migrations.AddField(
            model_name="order",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_made",
                to="app.user",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(to="app.product"),
        ),
        migrations.AddField(
            model_name="order",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_received",
                to="app.user",
            ),
        ),
    ]
