# Generated by Django 4.2.16 on 2024-10-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("WEAPON", "Weapon"),
                    ("LEGO", "Lego"),
                    ("FIGURES", "Figures"),
                    ("POSTER", "Poster"),
                    ("COLLECTIBLE", "Collectible"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
    ]
