# Generated by Django 4.2.16 on 2024-11-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_cart_favourite_follower_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admin",
            field=models.BooleanField(default=False),
        ),
    ]
