# Generated by Django 4.2.16 on 2024-11-08 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_order"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Favourite",
            new_name="Favorite",
        ),
    ]
